# Postgres 9.3.0.0
#
development:
  adapter: postgresql
  encoding: unicode
  database: hi5exchange
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: hi5exchange
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: hi5exchange
  pool: 5
  timeout: 5000

